### ISSUE TITLE
Module Import Correction

### ISSUE THREAD

**Issue by bolshoibooze** [mypebble/django-pgviews#11]
it should be :

from django_pgviews import view as pg

and not " import django_postgres.view as pg"

**Comment by kennydude** [comment]
Thanks, typo on my part there!

**Comment by bolshoibooze** [comment]
You're welcome, other parts of the docs have the same issue too :-)

**Comment by kennydude** [comment]
I think I need to review the documentation at some point as it hasn't been updated in quite some time

**Comment by bolshoibooze** [comment]
Yap, that's a good idea. If i find any other issue, i'll let you know asap. Awesome work by the way, thanks for sharing
