### ISSUE TITLE
Switch CI system for better build matrix

### ISSUE THREAD

**Issue by codingjoe** [mypebble/django-pgviews#14]
Hi, I'd like to propose a switch to travis-ci.
I think thee is an advantage when it comes to the support of multiple python and Django versions.
Travis-CI has a more advanced build matrix.

I'd be willing to set it up. As a plus I could even do a full ['django-cc'](https://github.com/codingjoe/django-cc) integration.

Let me know if you're interested and I'll open up a PR.

**Comment by kennydude** [comment]
We use CircleCI here at Pebble for all of our products, so it would mean having one of our projects being odd.

**Comment by codingjoe** [comment]
@kennydude I totally get that.
How about tox? Tox has the means to provide a build matrix, with the added benefit of reusing it offline.
I could write you and integration for the currently supported versions if you'd like.

**Comment by codingjoe** [comment]
I added tox here #20 
This will add proper tests for all currently maintained python and Django versions.
