### ISSUE TITLE
cannot drop view whily syncing

### ISSUE THREAD

**Issue by anneFly** [mypebble/django-pgviews#15]
Hi,
we saw that there is an issue with syncing views, in case you change views that are dependencies for other views:

#### How to reproduce the error
1) create 2 Views like this
```
class Test1View(django_pgviews.View):
    sql = "SELECT last_name, email from auth_user;"

    class Meta:
        db_table = 'myapp_test1view'
        managed = False


class Test2View(django_pgviews.View):
    dependencies = [
        'myapp.Test1View',
    ]
    sql = "SELECT email from common_test1view;"

    class Meta:
        db_table = 'common_test2view'
        managed = False
```
2) run `manage.py sync_pgviews --force`

3) change the sql of `Test1View` to be `SELECT last_name, first_name, email from auth_user;`

4) run `manage.py sync_pgviews --force`
--> You will encounter the following error during sync:
`psycopg2.InternalError: cannot drop view myapp_test1view because other objects depend on it`

I will try to come up with a fix for this, unless you know another way how to get around this error.

**Comment by kennydude** [comment]
I don't know of a workaround at the moment. All I can think of is ordering the views internally to deal with dependencies

**Comment by scott-w** [comment]
Perhaps the sync has an internal step that builds a dependency tree, drops all the dependant views and recreates them in order?

**Comment by scott-w** [comment]
At present, the workaround we use is to `drop_pgviews`, `migrate`, then `sync_pgviews`

**Comment by anneFly** [comment]
thanks for your answers. I was also thinking of droping the views before migrate. But since migrations can take a while sometimes, we would not have the views in our db for that time (which is not an option for us and our use case)

I will dig into it a bit and see how this can be fixed the best way.
