### ISSUE TITLE
importerror with django 1.9

### ISSUE THREAD

**Issue by jheld** [mypebble/django-pgviews#17]
I have the library installed, and I'm running django 1.9 and python3.5

Here is the error I get on startup:
ImportError: No module named 'django_pgviews'
It is listed in my installed_apps.
I'm running version 0.1.0.
Ideas?

**Comment by kennydude** [comment]
Hi jheld,

You can try manually importing it with the Django shell (`python manage.py shell`) using `import django_pgviews`

That should display a more detailed error with importing if there is one.

**Comment by jheld** [comment]
@kennydude through the shell, there are no issues.

**Comment by kennydude** [comment]
Sounds like you have an issue with your import path with your application

**Comment by jheld** [comment]
had an old virtualenv and thus...nothing installed at that name. Thanks!
