### ISSUE TITLE
querying the MaterializedView

### ISSUE THREAD

**Issue by jheld** [mypebble/django-pgviews#18]
I have a materialized view that is a cached set of results from a few database tables.

I see that you have an option for a model = ForeignKey() field in the read only MV, but I can't quite use that...unless you're just calling it "model" to make it simple to look at, instead of being a hook the app knows about.

Basically, when I call MyMV.objects.count(), I get an error that the relation doesn't exist. I have managed=True, abstract=False, and I have the db_name set correctly. Calling refresh on the class in ipython does seem to work (takes awhile to finish anyway).

Any ideas?

**Comment by kennydude** [comment]
I don't know what you mean by `model = ForiegnKey()` as the fields inside of a View are the same as a standard django model.

You want `managed=False` to tell Django not to try and sort out the table itself.

Also make sure to sync the views with `python manage.py sync_pgviews`

**Comment by jheld** [comment]
You have an example model in the your tests that uses that.

Seems the problem is related to the MV name being quoted in the FROM clause in the query. I imagine that is django's fault.

Ah, typo, managed is False. I am aware of its use, but thanks for explaining anyway.

**Comment by scott-w** [comment]
Thanks for this @jheld. I'll close the issue. Feel free to comment if you feel there's still something to resolve.
