### ISSUE TITLE
0.5.1 PYPI build fails looking for README.md

### ISSUE THREAD

**Issue by mlindemu** [mypebble/django-pgviews#30]
Receive the following message when I run pip install django-pgviews

Downloading django-pgviews-0.5.1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-FEpTji/django-pgviews/setup.py", line 9, in <module>
        LONG_DESCRIPTION = open('README.md').read()
    IOError: [Errno 2] No such file or directory: u'README.md'

Running pip install "django-pgviews<0.5.1" installs the library correctly.

**Comment by scott-w** [comment]
Hi @mlindemu thanks for reporting this! It seems the issue is specific to Python 2.

I've just pushed out 0.5.3 to fix this.

Regards
Scott
