### ISSUE TITLE
Tests materialized views

### ISSUE THREAD

**Issue by andrehenriquemendes** [mypebble/django-pgviews#59]
Hey guys,

I have a issue when test materialized views with pytest.

Basically, when I refresh the materialized views by endpoint works, but when I refresh with tests, don't works.

The refresh method works, but don't update datas on materialized view.

Thank you!

**Comment by mikicz** [comment]
Hi. Could you maybe post a snippet of the testing code, so we can see when/how you're refreshing the materialized view?

**Comment by andrehenriquemendes** [comment]
> Hi. Could you maybe post a snippet of the testing code, so we can see when/how you're refreshing the materialized view?

Hi, @mikicz!
After create the original instance, it call refresh_materialized_view() to refresh

```
def refresh_discounts_materialized_view(self):
      with connection.cursor() as cursor:
              cursor.execute(f'REFRESH MATERIALIZED VIEW discount_checker_setup_view')

def test_list_discounts(self, mocked):
        self.create_discount() # create original instance
        self.refresh_discounts_materialized_view()
```

PS:

- The name "discount_checker_setup_view" is correct

**Comment by mikicz** [comment]
Have you tried refreshing with this instead of the cursor query?

```
DiscourdCheckerSetupView.refresh()
```

(assuming that's the class where you're defining the mat. view)

**Comment by andrehenriquemendes** [comment]
I tried too, it was my first attempt

**Comment by mikicz** [comment]
Hm, that's strange them. It's hard for me to judge without seeing more of the code unfortunately.
I use materialized views with pytest and they work fine, so not sure what's exactly going on.

Two things I'd investigate:
  - What database the connection is using you're using to create the cursor (is it the same on as the one create_discount method uses?
   - Are transactions here at play? Django tests usually run within a single transaction, which could mean something iffy is going on with them, idk how well would this play with the transactions.
    - Before running the refresh, checking the data is actually in the table the mat view is supposed to load from...

**Comment by andrehenriquemendes** [comment]
@mikicz, can you show me how is your model and migration? Just to compare with mine. I have been with this problem for days

**Comment by mikicz** [comment]
I can't provide any actual examples from my codebase unfortunately. But setup-wise there's nothing special, a regular django model with standard migrations and a materialized view without any special stuff, like it's in the documentation: https://github.com/mikicz/django-pgviews#materialized-views
